<h1>Introduction</h1>

<p>The zf1-doctrine application is a simple project I created to learn how to incorporate and use the Doctrine ORM in a Zend Framework, Zend Tool created application. The application demonstrates some of Doctrines most basic concepts including, creating successful YAML schema files, and one-to-one, one-to-many, and many-to-many CRUD operations</p>

<p>Some of the immediate goals of the application besides learning how to use Doctrine, were to ensure that Doctrine result sets could be easily manipulated with Zend Form and Zend Paginator, stuff that you would use in any other daily work flow. </p>

<h3>Requirements</h3>

<p>This application was developed using the latest and the greatest, well at the time of writing, <a href="http://www.php.net">PHP 5.3.5</a>, and <a href="http://framework.zend.com">Zend Framework 1.11.3</a> and <a href="http://www.doctrine-project.org/">Doctrine 1.2.0.</a></p>

<h3>Deploying</h3>

<p>You will need to follow the official Zend Framework guidelines on creating an application including creating an entry in your servers hosts file and defining an Apache virtual host configuration entry that points to the applications public root directory.</p>

<h3>Questions or Comments?</h3>

<p>Email: <a href="mailto:tom@tomshaw.info">tom@tomshaw.info</a></p>
