<?php $this->headLink()->appendStylesheet('/css/table.css'); ?>
<h2>Many To Many Groups</h2>
<p>To add a user to a group, edit the user and select the groups to assign.</p>
<form id="form" method="get" action="/manytomany/edit">
<?php echo $this->formHidden('id') ?>
<table class="data-list" summary="Data Listing">
  <!--<caption>Many To Many Relations</caption>-->
  <thead>
    <tr>
      <th scope="col" width="5%" align="center">ID</th>
      <th scope="col">Name</th>
      <th scope="col" align="center">Group Count</th>
      <th scope="col">Created</th>
      <th scope="col">Updated</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <td colspan="4" align="right">Total:</td>
      <td colspan="1"><?php echo $this->total ?></td>
    </tr>
  </tfoot>
  <tbody>
    <?php foreach($this->rows as $row): ?>
    <?php $colour = $this->cycle(array("row1","row2"))->next(); ?>
    <tr class="<?php echo $colour ?>" onMouseOver="this.bgColor='#c6bebe';" onMouseOut="this.bgColor='<?php echo $colour ?>';">
      <td style="text-align: center;"><?php echo $this->formSubmit('submit', 'Edit', array('onclick' => "this.form.id.value='{$row->id}'", "class" => "button", "title" => 'Edit')) ?></td>
      <td><a href="/hasone/edit/id/<?php echo $row->id ?>"><?php echo $row->email ?></a> [<?php echo $row->email ?>]</td>
      <td align="center"><strong><?php echo count($row->UserGroups) ?></strong></td>
      <td><?php echo $row->updated_at ?></td>
      <td><?php echo $row->created_at ?></td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>
</form>