<?php $this->headLink()->appendStylesheet('/css/form.css')->appendStylesheet('/css/table.css'); ?>
<h4><?php echo $this->email ?></h4>
<?php echo $this->form ?>
<form id="form" method="get" action="/hasmany/delete">
<?php echo $this->formHidden('id') ?>
<table class="data-list" summary="Data Listing">
  <thead>
    <tr>
      <th scope="col" width="5%" align="center">ID</th>
      <th scope="col">Comment</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <td colspan="1" align="right">Total:</td>
      <td colspan="1"><?php echo $this->total ?></td>
    </tr>
  </tfoot>
  <tbody>
    <?php foreach($this->rows as $row): ?>
    <?php $colour = $this->cycle(array("row1","row2"))->next(); ?>
    <tr class="<?php echo $colour ?>" onMouseOver="this.bgColor='#c6bebe';" onMouseOut="this.bgColor='<?php echo $colour ?>';">
      <td style="text-align: center;"><?php echo $this->formSubmit('submit', 'Delete', array('onclick' => "this.form.id.value='{$row->id}'", "class" => "button", "title" => 'Delete')) ?></td>
      <td><?php echo $row->comment ?></td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>
</form>
<?=$this->paginationControl($this->rows, 'Elastic', 'pager.phtml');?>