<?php $this->headLink()->appendStylesheet('/css/table.css'); ?>
<h2>Has Many Comments</h2>
<p>Using this controller we are going to add many comments per user. This is a one to many relationship.</p>

<form method="get" action="/hasmany/add">
  <select name="id" id="id">
    <?php foreach(Doctrine_Query::create()->from('Model_User u')->execute() as $user): ?>
    <option value="<?php echo $user->id; ?>"><?php echo $user->email; ?></option>
    <?php endforeach; ?>
  </select>
  <input type="submit" name="submit" value="Select User" />
</form>

<form id="form" method="get" action="/hasone/edit">
<?php echo $this->formHidden('id') ?>
<table class="data-list" summary="Data Listing">
  <!--<caption>One to One Relations</caption>-->
  <thead>
    <tr>
      <th scope="col" width="5%" align="center">ID</th>
      <th scope="col">Name</th>
      <th scope="col" align="center">Comments</th>
      <th scope="col">Created</th>
      <th scope="col">Updated</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <td colspan="4" align="right">Total:</td>
      <td colspan="1"><?php echo $this->total ?></td>
    </tr>
  </tfoot>
  <tbody>
    <?php foreach($this->rows as $row): ?>
    <?php $colour = $this->cycle(array("row1","row2"))->next(); ?>
    <tr class="<?php echo $colour ?>" onMouseOver="this.bgColor='#c6bebe';" onMouseOut="this.bgColor='<?php echo $colour ?>';">
      <td style="text-align: center;"><?php echo $this->formSubmit('submit', 'Edit', array('onclick' => "this.form.id.value='{$row->id}'", "class" => "button", "title" => 'Edit')) ?></td>
      <td><a href="/hasone/edit/id/<?php echo $row->id ?>"><?php echo $row->email ?></a> [<?php echo $row->email ?>]</td>
      <td align="center"><?php echo count($row->Comment) ?></td>
      <td><?php echo $row->updated_at ?></td>
      <td><?php echo $row->created_at ?></td>
    </tr>
    <?php foreach($row->Comment as $comment): ?>
    <tr class="<?php echo $colour ?>">
      <td colspan="5"><?php echo $comment->comment ?></td>
    </tr>
    <?php endforeach; ?>
    <?php endforeach; ?>
  </tbody>
</table>
</form>